# Generated by Django 4.0.4 on 2022-07-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_nonregistereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregistereduser',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
