# Generated by Django 4.0.4 on 2022-07-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_nonregistereduser_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonregistereduser',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
