# Generated by Django 4.0.4 on 2022-07-10 19:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_nonregistereduser_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonregistereduser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
