# Generated by Django 4.0.5 on 2022-08-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_nonregistereduser_phone_number'),
        ('event', '0015_alter_registereduser_date_of_birth'),
    ]

    operations = [
    ]
