# Generated by Django 4.0.5 on 2022-08-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_merge_20220805_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='interested_events',
            field=models.ManyToManyField(db_table='user_interested_events', to='event.event'),
        ),
    ]
