# Generated by Django 4.0.5 on 2022-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_registereduser_going_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='attended_events',
            field=models.ManyToManyField(db_table='user_attended_events', related_name='attended_users', to='event.event'),
        ),
    ]
