# Generated by Django 4.0.5 on 2022-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_registereduser_hosted_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='attended_events',
            field=models.ManyToManyField(db_table='user_attended_event', related_name='attended_users', to='event.event'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='going_events',
            field=models.ManyToManyField(db_table='user_going_event', related_name='going_users', to='event.event'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='hosted_events',
            field=models.ManyToManyField(db_table='user_hosted_event', related_name='hosting_users', to='event.event'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='interested_events',
            field=models.ManyToManyField(db_table='user_interested_event', related_name='interested_users', to='event.event'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='invited_events',
            field=models.ManyToManyField(db_table='user_invited_event', related_name='invited_users', to='event.event'),
        ),
    ]
