# Generated by Django 4.0.4 on 2022-08-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_registereduser_attended_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregistereduser',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_link', models.ImageField(upload_to='media/')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
