# Generated by Django 4.0.5 on 2022-09-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_registereduser_attended_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregistereduser',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
