# Generated by Django 4.0.4 on 2022-07-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_nonregistereduser_alter_event_photo_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='NonRegisteredUser',
        ),
    ]
